version: '2.1'

services:
  # mysql:
  #   restart: always
  #   image: mariadb:latest
  #   ports:
  #     - 3306
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret

  # phpmyadmin:
  #   restart: always
  #   image: phpmyadmin/phpmyadmin:latest
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:80"
  #   volumes: 
  #     - ./docker/php/ext/02-development.ini:/usr/local/etc/php/conf.d/php.ini  
  #   environment:
  #     - PMA_USER=root
  #     - PMA_PASSWORD=secret
  #     - PMA_HOST=mysql

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=nautdejong.local.betaserver.nl
      - NGINX_PORT=80

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    ports:
      - "8081:8081"
    volumes:
        - ./../:/var/www
        - ./uploads:/var/uploads
        - ./docker/php/ext/02-development.ini:/usr/local/etc/php/conf.d/02-development.ini

# volumes:
#   groundwork_mysql:
